### ISSUE TITLE
제안) html과 css 파일 연결

### ISSUE THREAD

**Issue by hae9** [fastcampus-team4/FibonaChicken#3]
## 설명

html 기본구조를 완성하고 css 파일 연결하겠습니다.

## 할일

- [x] html 기본구조 완성
- [x] css 파일 연결
- [x] js 파일 연결

**Comment by ulgoon** [comment]
Don't forget heading text

## Description

## Tasks
